// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFKDh3W9wNdTaJiffrBXt2gKo0jYa1jp0',
    appId: '1:44412008637:web:c73218d95560a457b25fd4',
    messagingSenderId: '44412008637',
    projectId: 'inventory-with-flutter',
    authDomain: 'inventory-with-flutter.firebaseapp.com',
    databaseURL: 'https://inventory-with-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-with-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmcUj-7DqLSQeVMKZTfyGOf2D1O2cT-tk',
    appId: '1:44412008637:android:7073762d81b45091b25fd4',
    messagingSenderId: '44412008637',
    projectId: 'inventory-with-flutter',
    databaseURL: 'https://inventory-with-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-with-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL-9CEe3WnQAG1TPWXSsrwAD9L-0ui6GI',
    appId: '1:44412008637:ios:46dc5079da3f8276b25fd4',
    messagingSenderId: '44412008637',
    projectId: 'inventory-with-flutter',
    databaseURL: 'https://inventory-with-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-with-flutter.firebasestorage.app',
    iosBundleId: 'com.example.inventorySystem',
  );

}